config/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views
from board.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base_views.index),                     #127.0.0.1:8000/
    path('board/', include('board.urls')),     #127.0.0.1:8000/board/
    path('common/', include('common.urls')),   #127.0.0.1:8000/common/
    path('poll/', include('poll.urls')),

]

poll/urls.py
from django.urls import path
from poll import views


app_name ='poll'

urlpatterns = [
    path('', views.index, name='index'),                # 127.0.0.1:8000/poll/
    path('<int:pk>/', views.detail, name='detail'),      #127.0.0.1:8000/poll/1
    path('<int:pk>/vote/', views.vote, name='vote')  #127.0.0.1:8000/poll/1/vote

]

poll/models.py
from django.db import models

# 질문 클래스(테이블) 생성
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.question_text

# 선택 클래스 생성
class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_text

poll/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from poll.models import Question

@login_required(login_url='common:login_view')
def index(request):
    question_list = Question.objects.all()
    return render(request, 'poll/index.html', {'question_list': question_list})

def detail(request, pk):
    question = Question.objects.get(id=pk)
    return render(request, 'poll/detail.html', {'question': question})


def vote(request, pk):
    question = Question.objects.get(id=pk)
    if request.method == "POST":
        try:
            choice = request.POST['choice']
        except:
            error = '항목을 선택하세요.'
            return render(request, 'poll/detail.html',
                          {'question':question, 'error':error})
        else:
            sel_choice = question.choice_set.get(id=choice)
            sel_choice.votes += 1
            sel_choice.save()
            return render(request, 'poll/result.html', {'question':question})
    else:
        return render(request, 'poll/detail.html', id=pk)

templates/poll/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>설문 항목</title>
    {% load static %}
    <link rel="stylesheet" href="{%static 'poll/css/style.css' %}">
    <link rel="stylesheet" href="{%static 'poll/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'board/css/style.css/' %}">
</head>
<body>
{% include 'navbar.html' %}
<div id="container">
    <section>
        <form action="{% url 'poll:vote' question.id %}" method="post">
            {% csrf_token %}
            <div class="card" style ='width: 50rem;'>
                <div class="card-body">
                    <fieldset>
                        <legend>{{ question.question_text }}</legend>
                        {% if error %}
                            <p style="color: #f00;">{{ error }}</p>
                        {% endif %}
                        {% for choice in question.choice_set.all %}
                        <p>
                            <input type="radio" name="choice" value="{{ choice.id }}">
                            <label>{{ choice.choice_text }}</label>
                        </p>
                        {% endfor %}
                    </fieldset>
                    <p><input type="submit" value="투표" class="btn btn-success"></p>
                </div>
            </div>
        </form>
        <div class="question_form"></div>
    </section>
</div>
{% include 'footer.html' %}
</body>
</html>

templates/poll/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>설문 조사 페이지</title>
    {% load static %}
    <link rel="stylesheet" href="{%static 'poll/css/style.css' %}">
    <link rel="stylesheet" href="{%static 'poll/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'board/css/style.css/' %}">
</head>
<body>
{% include 'navbar.html' %}
<div id="container">
    <h2>설문조사에 응해주시기 바랍니다.</h2>
    <div class="card">
        <div class="card-body">
            <section>
                {% if question_list %}
                <ul>
                    {% for question in question_list %}
                    <li>
                        <h4>
                            <a href="{% url 'poll:detail' question.id %}" class="badge badge-success">
                            {{ question.question_text }}</a>
                        </h4>
                    </li>
                    {% endfor %}
                </ul>
                {% else %}
                    <p>설문이 없습니다.</p>
                {% endif %}
            </section>
        </div>
    </div>
    <div class="question_form"></div>
</div>
{% include 'footer.html' %}
</body>
</html>

templates/poll/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>투표 결과</title>
    {% load static %}
    <link rel="stylesheet" href="{%static 'poll/css/style.css' %}">
    <link rel="stylesheet" href="{%static 'poll/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'board/css/style.css/' %}">
</head>
<body>
{% include 'navbar.html' %}
<div id="container">
    <section>
        <div class="card" style ='width: 50rem;'>
            <div class="card-body">
                <h2>{{ question.question_text }}</h2>
                <ul>
                    {% for choice in question.choice_set.all %}
                    <li>
                        Votes : {{ choice.choice_text }} [ {{ choice.votes }} ]
                    </li>
                    {% endfor%}
                </ul>
                <p><button type="button" onclick="location.href='/poll/'" class="btn btn-success">설문 목록</button></p>
            </div>
        </div>
        <div class="question_form"></div>
    </section>
</div>
{% include 'footer.html' %}
</body>
</html>